export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_PATIENT = 'GET_PATIENT'
export const GET_PATIENTS = 'GET_PATIENTS'
export const PATIENT_ERROR = 'PATIENT_ERROR'
export const LOGOUT = 'LOGOUT'